name: generate_swagger_endpoint
owner: suica.dev
description: A command-line to extract endpoint from swagger.json.
homepage: https://pub.dev/packages/generate_swagger_endpoint
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # path: ^1.8.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
