name: generate_swagger_endpoint
owner: suica.dev
description: This command-line tool extracts endpoints from a swagger.json file. It generates a class containing the endpoints as static properties.
repository: https://github.com/SuicaLondon/generate_swagger_endpoint
homepage: https://pub.dev/packages/generate_swagger_endpoint
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # path: ^1.8.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
